import { sendGet, sendPost } from './index'

export const getQuotationList = (params) => sendGet('admin/quotations', params)
export const multiDeleteQuotation = (params) => sendPost('admin/quotations/multi-delete', params)
export const getQuotationDetail = (id) => sendGet(`admin/quotations/${id}/detail`)
export const createQuotation = (params) => sendPost('admin/quotations/create', params)
export const getExportQuotationCSV = (params) => sendGet('admin/quotations/export', params)
export const updateQuotation = (params) => sendPost('admin/quotations/update', params)
export const getAllQuotationList = (params) => sendGet('admin/quotations/all', params)
export const downloadPDF = (params) => sendGet('admin/quotations/export-pdf', params)
export const getRevenue = (params) => sendGet('admin/quotations/estimated-revenue', params)
export const handleDiscountChange = (params) => sendPost('admin/quotations/update-discount', params)
export const sendApproval = (params) => sendPost('admin/quotations/send-approve', params)
export const handleApproveQuotation = (params) => sendPost('admin/quotations/approve', params)
export const getTotalAmountQuotation = (params) => sendGet('admin/quotations/total-amount', params)
